apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rfr1m6ttb-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c2f86674c8e2abb0d80b860b8fdca178c5dbe625@sha256:58c270a4d5455a59e2e44b8e8e06604cba0e18cc5e1130c0a54d85c466c7b55e
          name: container-image
